### ISSUE TITLE
Update from 1.1.0 to 1.1.1 creates two instances of OWS

### ISSUE THREAD

**Issue by lokendra-lsr** [karakun/OpenWebStart#143]
openwebstart version 1.1.1

Issue: Update from 1.1.0 to 1.1.1 creates two instances of OWS

How to reproduce it:
1. Install 1.1.0
2. Check for update
3. Proceed with update installation of 1.1.1 and select installation for current user
4. You will find two installed version on same machine.
![OWS_1 1 1_issue](https://user-images.githubusercontent.com/59013254/71075574-4b515600-21aa-11ea-9cc1-93945a2bcc43.PNG)

**Comment by sclassen** [comment]
Can you tell us the OS you are using

**Comment by lokendra-lsr** [comment]
I am using windows 10.
Additional information, I have installed 1.0.0 and updated to 1.1.0 using
OWS update process and then updated to 1.1.1

**Comment by hendrikebbers** [comment]
We changed the installer for 1.1.1 so that you now can decide if you want to install it for all users of a system or for a single user. The previews version always installs it for all users. Maybe you selected the single user installation when doing the update. I never checked but I can assume that this could end in such behaviour.

I'm not familiar with Windows but at MacOS the 2 installation types will be installed in 2 differenten folders and therefore it might be possible to have both installed:
All users -> /Applications/OpenWebStart
Single user -> /Users/USER_NAME/Applications/OpenWebStart

**Comment by lokendra-lsr** [comment]
Yes, you are right.
I have selected single user and have similar observation.
