### ISSUE TITLE
HTTP User-Agent not allowed to be overriden by System.setProperty()

### ISSUE THREAD

**Issue by sbodmer** [karakun/OpenWebStart#145]
I folks,

We need to override the http user agent to access some web services ("http.agent" system property).
When we start the .jnlp from web page, the user agent set in the jnlp (&lt;property&gt;) is correctly overridden, and everything works fine, but when we use the desktop shortcut, the message below is shown in the OpenWebStart console

> Cannot set HTTP User-Agent as a connection has been opened before reading the JNLP file

and the property is not overridden and our http request fails...

Our own traffic (sniffer) debug shows us that the http header for the user agent is not overridden when the .jlnp is started from desktop shortcut (tested under Linux and Windows 10).

Is this a bug or a "security" feature ?

Thanks for any help.

**Comment by sclassen** [comment]
This is almost certainly a bug.
What is happening is that OWS will download the jnlp from the server to make sure it has the latest updates and only after doing so it will analyze the properties within the jnlp.
But by doing so it cannot change the user agent any more because it already opened a connection for downloading the jnlp file.

**Comment by sbodmer** [comment]
I understand... perhaps solving the problem will be to open a simple socket connection to the .jlnp source without using the URL classes for checking the last version...
