### ISSUE TITLE
JNLP applications are not opening be default via java open web start launcher in MAC 

### ISSUE THREAD

**Issue by yuvraj18yadav** [karakun/OpenWebStart#148]
After installing the open web start in Mac os. I opened the JNLP application. By default, it is opening via the JAVA web start.  For opening it VIA open web start launcher the user needs to click on open with-> select open web start then only the JNLP application is launched via open web start
<img width="237" alt="Screenshot 2019-12-26 at 11 54 49 AM" src="https://user-images.githubusercontent.com/16862496/71461770-fbd8de80-27d6-11ea-819b-c2e6b6d1d005.png">
. 
While installing the open web start I have  Enabled the checkbox to associate the.JNLP suffix with OpenWebStart

**Comment by sclassen** [comment]
@hendrikebbers can you reproduce this behavior on your mac?

**Comment by netopyr** [comment]
This is correct behavior. On Mac an application cannot change the default application for a file-suffix, if there is already one defined. The new application can only be added. This seemed to have worked, because otherwise you would not see OpenWebStart in the context-menu.
You can change the default application manually. Click "Other..." in the context menu and pick OpenWebStart in the dialog. At the bottom check "Always Open With". Once you do that, OpenWebStart will be used for all JNLP-files.

**Comment by yuvraj18yadav** [comment]
> This is correct behavior. On Mac an application cannot change the default application for a file-suffix, if there is already one defined. The new application can only be added. This seemed to have worked, because otherwise you would not see OpenWebStart in the context-menu.
> You can change the default application manually. Click "Other..." in the context menu and pick OpenWebStart in the dialog. At the bottom check "Always Open With". Once you do that, OpenWebStart will be used for all JNLP-files.

In windows 10 .jnlp applications opens by default via open jws launcher . I did not do any kind of settings for that where as in mac it doesnt open by default using open jws launcher .  Its bit strange that On windows 10 it is opening by default where as in Mac it is not .
