### ISSUE TITLE
A zip-package without installer would be nice

### ISSUE THREAD

**Issue by AlBundy33** [karakun/OpenWebStart#182]
For local tests I'd like to have zip-package without the requirement to run an installer.

**Comment by sclassen** [comment]
The installer is necessary to register file extensions with the OS.
If you installed it on one machine you could copy the jar to another machine and launch it with
`java -cp <path-to-jar> PhaseTwoWebStartLauncher <JNLP> [ARGUMENTS]`

**Comment by AlBundy33** [comment]
With the zip-file you can also provide a command or reg-file to register the file-extension.
I think if someone downloads the zip-file they should know that they have to register the extension manually.

**Comment by janakmulani** [comment]
@AlBundy33 

This issue is currently not part of our road map. Discussing such topic and finding a solution that will work for all OWS users can not be done as part of our free community support. We provide commercial support for OpenWebStart (https://openwebstart.com/support/) and even provide to work based on time & material. If this is an option for you please contact us at openwebstart@karakun.com
If you interested in discussing this issue you are more than welcome to join our free webinar next week: https://mailchi.mp/karakun/openwebstart-v12-faqsession

If this is not an option for you it is always possible to provide a Pull Request.
