### ISSUE TITLE
OSX Shortcut never creates

### ISSUE THREAD

**Issue by FoxyBOA** [karakun/OpenWebStart#256]
Part of my JNLP file looks like

```
    <information>
        <title>XYZ</title>
        <vendor>ABC</vendor>
        <homepage href="http://www.url.com"/>
	<icon href="images/logo.gif" width="64" height="64"/>
	<icon kind="splash" href="images/splash.jpg"/>
    <shortcut online="true" install="true">
    	<desktop/>
    	<menu submenu="Product title"/>
    </shortcut>
    </information>
```

It works pretty well for OSX and Windows (i.e. create shortcuts for both OS). I'm investigating migration from JWS to OWS and stuck to desktop shortcuts.

It never creates. I tried any combinations of `<icon/>` tag (kind="shortcut", size ...="32", empty size, multiple sizes) as well as desktop integration value shortcut handling (ask user, always allow,  ask if hinted etc.).

No luck. Please, point me out what I'm doing incorrectly.

P.S. Yes with JWS everything works as expected.

**Comment by sclassen** [comment]
Yes. We are having issues with creating shortcuts for OSX.
We are lacking knowledge in this area and a contribution would be highly welcome.
If you feel confident to help us I can explain the issues we face in detail.

**Comment by FoxyBOA** [comment]
Hi @sclassen . Not sure if I have appropriate knowledge, but I wanna try if it is possible.

**Comment by sclassen** [comment]
OK so here we go:
We struggled to create a shortcut in the first place. We were trying to create an executable shell file which would then start OWS and pass the right URL.
This works for JNLP files on the local file system. But as soon as you try to open a JNLP file over http or https the browser was opened instead of OWS.
But maybe creating an executable shell file is not the way to go on OSX and we need some other approach...

So if you could help us by providing a java class which can create shortcuts we can then incorporate this into OWS.

**Comment by vnashkev** [comment]
Hi.
The situation for OS X is even worse.
The Application link created under /Applications folder does not work at all.

The reason is a wrong path within start.sh script : 
            `open -a "/Applications/OpenWebStart javaws.app" "https://server/app.jnlp"`

The right path should be "/Applications/OpenWebStart/OpenWebStart javaws.app".
(I suppose this happens because of install4j bug).

Since we finally do have support for JNLP/JNLPS url-schemas the fix is as easy as 
           `open jnlps://server/app.jnlp`

Now back to the desktop-link.
Assume we have application under /Applications/jnlp.app created by OpenWebStart.
Creation of symbolic link on Desktop solves the problem.

`ln -s /Applications/jnlp.app /Users/user/Desktop/jnlp`

If you agree with this approach I can contribute.

Thanks a lot for your work, 
Vitali

**Comment by sclassen** [comment]
@hendrikebbers can you take this from here. Thanks

**Comment by sclassen** [comment]
Maybe also interesting:
https://stackoverflow.com/questions/48600128/mac-os-x-lnk-with-argument#answer-48608779
