### ISSUE TITLE
Additional JVM arguments are not passed to launched JVM

### ISSUE THREAD

**Issue by akuhtz** [karakun/OpenWebStart#257]
Hello,

Additional JVM arguments are not passed to the launched JVM. If I want to provide 
`javaws -J-Djava.net.preferIPv4Stack=true  http://localhost/test.jnlp`

then I can see in the log that the `-Djava.net.preferIPv4Stack=true` is missing in the call of the java.exe launch:
```[MESSAGE_ALL][Tue May 05 10:48:48 CEST 2020] About to launch external with commands: '["C:\Program Files\BellSoft\LibericaJRE-11\bin\java.exe", -Xbootclasspath/a:C:\Users\*****\AppData\Local\Programs\OpenWebStart-3\openwebstart.jar, -Xms32m, -Xmx448m, @C:\Users\*****\AppData\Local\Programs\OpenWebStart-3\itw-modularjdk.args, net.sourceforge.jnlp.runtime.Boot, -Xnofork, -verbose, http://localhost/test.jnlp]'```

The only hack to currently get it in with OpenWebStart v3.0.0-alpha1 is adding it to `itw-modularjdk.args` that lets the application start :-)

**Comment by sclassen** [comment]
Because of security reasons only explicitly whitelisted arguments can be passed to the applications.

The argument you mention is a property. Properties can also be specified as a resource in the JNLP.
This is the recommended way of passing properties. Unfortunately some properties need to be passed to the JVM as argument because they take effect before OpenWebStart has a chance to set them. If this is the case please report this and we will check if preferIPv4Stack can be added to the whitelist.

Also note that the workaround with the itw-modularjdk.args will not work in future versions as the file has been replaced by an other mechanism.

**Comment by akuhtz** [comment]
The JVM args should only be applied locally by launching `javaws` with additional JVM args (so it's not the plan or need to add them to the JNLP). This works for the "first call" of `javaws.exe` but when `java.exe` is launched later on (see log above) these JVM args are not passed to `java.exe`.
We have currently the case that we work over VPN and connect and download to remote server only works if `-Djava.net.preferIPv4Stack=true` is provided to `java.exe`. 

In the meantime I was testing with (old) Oracle Webstart and it does not work there either. I was trying to add it permanently to some local configuration files (JRE) but without luck so far.

**Comment by sclassen** [comment]
Yes this is the desired behavior.
OWS works in 2 phases.

1) a JVM is launched and the JNLP is loaded and parsed. From the data in the JNLP OWS will determine which Java Version is required and what additional arguments are needed

2) a new JVM is launched according to the data from phase 1. This new JVM will execute the application

As a consequence there are no arguments passed from JVM1 to JVM2.
What you can try is to set java.net.preferIPv4Stack=true as an environment variable in Windows/Linux/MacOS. Maybe Java is picking it up and it will be available in phase 2.

**Comment by akuhtz** [comment]
Your answer made me thinking again and we found a solution. Adding the environment variable:
```JAVA_TOOL_OPTIONS=-Djava.net.preferIPv4Stack=true```
solves this issue.
