### ISSUE TITLE
create a openwebstart installer

### ISSUE THREAD

**Issue by undergraver** [karakun/OpenWebStart#291]
I am wondering if there is a way to make our own openwebstart installer. 

In case this is not easily achievable, how can I test local versions that I am building (from within IntelliJ-IDEA)?

Any pointers in this direction? I can make a README and even contribute with automation scripts.

**Comment by hendrikebbers** [comment]
Hi,
currently it is not possible to create a custom OWS installer since we use commercial tools to create the native installers and executables. In IntelliJ you can start a JNLP application or open the OWS settings by starting the correct main with given parameters. @janakmulani do we have a doc for that?

As part of our commercial support we offer custom installers for costumers. You can find more information [here](https://openwebstart.com/support/#paid-support-packages).

**Comment by sclassen** [comment]
You can build local versions using maven.
First checkout and run `mvn clean install` for AdoptOpenJDK/IcedTea-Web
Then do the same for OpenWebStart.

The final openwebstart-x.x.x-SNAPSHOT.jar you can simply copy into your installation folder.
