### ISSUE TITLE
OpenWebStartLauncher exits without launcing the webstart (MacOS)

### ISSUE THREAD

**Issue by kelemenb-ewit** [karakun/OpenWebStart#365]
When I click on a jnlp, or JavaApplicationStub from console I see the OpenWebStart splash screen appear for a brief moment, but nothing else is started.
When starting from console I cannot see any error messages.
I can modify the settings, and whatnot, no problem there. Some months ago it worked just fine.
Can it be some stupid MacOS security that prevents applications to run?
Still I would expect some error message.

OpenWebStart version: 1.3.0
JVM: Amazon Corretto 1.8.0_275 JRE
OS: macOS Catalina 10.15.7

**Comment by sclassen** [comment]
Thanks for reporting this.

Could you help us locating the issue by providing logs and the JNLP file.

For the logs:
Open the settings and find the tab logging. Make sure log to file and debug logging is activated.
In the same window you will see the folder where all logs are written to.
Go to the folder and delete all log files which you see.
Then start the failing application once.
This should create between one and three log file.
Please attach all these files and the JNLP file to this issue.

Thanks again

**Comment by prampec** [comment]
Sorry this does not appears to be a real bug. What happened is that some windows appeared in the background I didn't have noticed. There was no icon in the Dock (aka. Task Bar), so after some day I now have realized to have these windows waiting for my interaction.
This might be a bug, because these windows should appear in the foreground.
![Screen Shot 2020-12-03 at 16 36 19](https://user-images.githubusercontent.com/10376327/101052114-8947b580-3586-11eb-8c91-0256595b3228.png)
